Raire service responses
DemocracyDevelopers/raire-service pull request #67
Opened 2024-04-18 11:27 UTC by vteague

This does error handling for the GenerateAssertions endpoint, for #41. This involves quite a lot of converting from raire-java errors. It also does #53.

The testing isn't yet ideal, because we don't really have a way of making most of the errors we're translating. More tests will make sense when #44 and #45 are done.

2024-04-22 01:27 UTC, michelleblom requested changes

2024-04-22 01:27 UTC, michelleblom commented on src/main/java/au/org/democracydevelopers/raireservice/controller/AssertionController.java
Typo: repository

2024-04-22 03:26 UTC, vteague commented on src/main/java/au/org/democracydevelopers/raireservice/response/Metadata.java
> +
I just meant that Colorado typically has the same risk limit for all the contests under audit (usually 3%) but that, in principle, raire-java will happily compute different difficulties as a function of an individual-contest risk limit. (I was justifying having a separate risk limit as part of the query for each contest, when everyone in colorado knows that it's always 3%). I have now tried to make this clearer.

2024-04-22 03:42 UTC, vteague commented on src/main/java/au/org/democracydevelopers/raireservice/service/GenerateAssertionsException.java
> +
I agree that generally distinguishing 'raire-java' from the 'raire-service' from 'raire in general' is a good idea. I've changed this where you pointed it out (or where I noticed) but might not have got them all (yet).

2024-04-23 00:01 UTC, michelleblom approved these changes

2024-04-23 00:01 UTC, merged